<?php 
    $layer = Mage::getSingleton('catalog/layer');
    $_category = $layer->getCurrentCategory();
    $currentCategoryId= $_category->getId();
    $children = Mage::getModel('catalog/category')->getCategories($currentCategoryId);
	
?>

<div class="sub-cat-section">
 <?php 
	$totalcat = count($children);
	if($totalcat > 0)
	{
		$row = 0; $m = 1;
		foreach ($children as $category)
		{
			if($row%2 == 0)
			{
				if($m == 1)
				{
				?>
 <ul class="sub-cat-row two-col">
  <?php } ?>
  <li class="sub-cat-colom">
   <?php 
							$cat = Mage::getModel('catalog/category')->load($category->getId());
							 
							?>
   <div class="subcat-image"> <a href="<?php echo $cat->getUrl(); ?>"> <img src="<?php echo Mage::getBaseUrl('media').'catalog/category/'.$cat->getThumbnail(); ?>"> </a> </div>
   <div class="subcat-desc"> <a class="cat-title" href="<?php echo $cat->getUrl(); ?>"><?php echo $cat->getName(); ?></a>
    <div class="cat-desc"> <?php echo $cat->getDescription(); ?> </div>
    <a class="cat-button" href="<?php echo $cat->getUrl(); ?>"><?php echo $this->__("Shop ").$cat->getName(); ?></a> </div>
  </li>
  <?php
					if($m == 2)
					{
					$m = 0;
					$row++;
					?>
 </ul>
 <?php }	 $m++; ?>
 <?php
			}else{
				if($m == 1)
				{
				?>
 <ul class="sub-cat-row three-col">
  <?php } ?>
  <li class="sub-cat-colom">
   <?php 
							$cat = Mage::getModel('catalog/category')->load($category->getId());
							 
							?>
   <div class="subcat-image"> <a href="<?php echo $cat->getUrl(); ?>"> <img src="<?php echo Mage::getBaseUrl('media').'catalog/category/'.$cat->getThumbnail(); ?>"> </a> </div>
   <div class="subcat-desc"> <a class="cat-title" href="<?php echo $cat->getUrl(); ?>"><?php echo $cat->getName(); ?></a>
    <div class="cat-desc"> <?php echo $cat->getDescription(); ?> </div>
    <a class="cat-button" href="<?php echo $cat->getUrl(); ?>"><?php echo $this->__("Shop ").$cat->getName(); ?></a> </div>
  </li>
  <?php
					if($m == 3)
					{
					$m = 0;
					$row++;
					?>
 </ul>
 <?php }	 $m++; 
		
				}
		}
	}
    ?>
</div>
<div class="best-product-deal">
 <div class="best-product-deal-title"> <div class="bestProHeading"><span><?php echo $this->__("BEST");?></span><?php echo $this->__(" PRODUCT DEAL"); ?></div> </div>
 <div class="best-product-deal-list">
  <?php
			$collection = Mage::getModel('catalog/product')->getCollection();
			$collection->addAttributeToSelect('*');  
			$collection->addFieldToFilter("is_feature",1);
			$collection->getSelect()->limit(5);
			if(count($collection) > 0)
			{
		?>
  <ul>
   <?php foreach ($collection as $_product): ?>
   <li class="item">
    <?php $_imgSize = 210; ?>
    <?php // The image size is locked at 210 for this for display purposes. CSS has it at 75% which should equate to 278px?>
    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image"> <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(210) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" /> </a>
    <div class="product-info">
     <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h3>
     <?php echo $_product->getShortDescription(); ?> <?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
     <div class="actions">
      <?php if ($_product->isSaleable()): ?>
      <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('BUY')) ?>" class="button btn-cart" onClick="setLocation('<?php echo $this->helper('checkout/cart')->getAddUrl($_product); ?>')"><span><span><?php echo $this->__('BUY') ?></span></span></button>
      <?php else: ?>
      <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
      <?php endif; ?>
     </div>
    </div>
   </li>
   <?php endforeach; ?>
  </ul>
  <?php 
			}
		?>
 </div>
</div>



<!--Static Html-->
