<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
    <div class="widget widget-new-products" style="margin-top:0px;">
        <div >
            <div class="widget-title" style="float:left;">
                <h2 style="font-size: 40px;color: #549F9D;"><span class="new" style="color:#EF9C2F "><strong><?php echo $this->__('BEST SELLING ') ?></strong></span> <?php echo $this->__('PRODUCTS') ?></h2>
            </div>
            <div style="padding-top: 43px;margin-left: 37%;"><hr></div>
        </div>
        <div class="widget-products">
            <?php echo $this->getPagerHtml() ?>
            <?php $_columnCount = $this->getColumnCount(); ?>
            <?php $i=0; ?>
            <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col-widget">
                <?php foreach ($_products->getItems() as $_product): ?>
                    <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                        <?php $_imgSize = 210; ?>
                        <?php // The image size is locked at 210 for this for display purposes. CSS has it at 75% which should equate to 278px?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
                            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(210) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" />
                        </a>
                        <div class="product-info">
                            <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h3>
                           <div class="prodhome-info"> <?php echo $_product->getShortDescription(); ?></div> 
                            <?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
                            
                            <div class="actions">
                                <?php if ($_product->isSaleable()): ?>
                                    <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('BUY')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('BUY') ?></span></span></button>
                                <?php else: ?>
                                    <p class="availability out-of-stock"><span> <?php echo $this->__('Out of stock') ?></span></p>
                                <?php endif; ?>
                            <?php/*<ul class="add-to-links">
                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <li><a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                <?php endif; ?>
                                <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                    <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                <?php endif; ?>
                            </ul>*/ ?>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>